import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";
import Footer from "./_components/footer";
import NavbarWrapper from "./_components/navbarWrapper";
import Navbar from "./_components/navbar";
import FooterWrapper from "./_components/footerWrapper";
import ScrollToTopButton from "./_components/scrollToTopButton";


export const metadata = {
  title: "tasbiya news",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body>
          <NavbarWrapper />
        <div className="main-content">
          <ScrollToTopButton/>
          {children}
        </div>
        <FooterWrapper/>
      </body>
    </html>
  );
}
